name: 全自动签到

on:
  schedule:
    # 每天北京时间（UTC+8）凌晨1点触发
    - cron: '0 17 * * *' # UTC时间，1 AM 北京时间是 5 PM UTC 前一天
  workflow_dispatch: # 手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: 加载代码
        uses: actions/checkout@v2

        
#      - name: 安装Chrome
#        id: setup-chrome
#        uses: browser-actions/setup-chrome@v1
#        with:
#          chrome-version: 120
#          install-chromedriver: true

          
      - name: 安装 Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果有需求文件
          

      - name: 签到脚本
        env:
#          CHROME: ${{ steps.setup-chrome.outputs.chrome-path }}  # 设置 Chrome 路径为环境变量
#          DRIVER: ${{ steps.setup-chrome.outputs.chromedriver-path }}  # 设置 Chrome 路径为环境变量
          UA: ${{ secrets.UA }}  # 使用 Secret 变量
          BOTTOKEN: ${{ secrets.BOTTOKEN }}  # 使用 Secret 变量
          USERID: ${{ secrets.USERID }}  # 使用 Secret 变量
          SOUTHPLUS: ${{ secrets.SOUTHPLUS }}  # 使用 Secret 变量
          ACGFUN: ${{ secrets.ACGFUN }}  # 使用 Secret 变量

        run: |
          python main.py  # 替换为实际的脚本名称
